import { SkillItem, UserRoleType } from '../types';

export const SKILL_GAP_BY_ROLE: Record<UserRoleType, SkillItem[]> = {
  software_engineer: [
    // AI Tooling
    {
      id: 'se-sk-1',
      name: 'Agentic Workflows & Multi-Step LLM Tool Calling',
      category: 'ai_tooling',
      isCurrent: false,
      isTarget: true,
      priority: 'high',
      description: 'Building autonomous loops with structured outputs, function calling, and self-correction cycles.',
      recommendedWeek: 5
    },
    {
      id: 'se-sk-2',
      name: 'Context Engineering & RAG Architecture',
      category: 'ai_tooling',
      isCurrent: false,
      isTarget: true,
      priority: 'high',
      description: 'Structuring knowledge embeddings, vector indices, and precise semantic context injection.',
      recommendedWeek: 3
    },
    {
      id: 'se-sk-3',
      name: 'AI Code Copilot Mastery (Cursor/Copilot/Claude Code)',
      category: 'ai_tooling',
      isCurrent: true,
      isTarget: true,
      priority: 'foundational',
      description: 'Using diff edits, workspace-wide symbol indexing, and multi-file code steering.',
      recommendedWeek: 2
    },
    {
      id: 'se-sk-4',
      name: 'LLM Evaluation & Adversarial Guardrails',
      category: 'ai_tooling',
      isCurrent: false,
      isTarget: true,
      priority: 'medium',
      description: 'Measuring hallucination rates, latency budgets, token economics, and prompt injection defense.',
      recommendedWeek: 6
    },
    // Human Edge
    {
      id: 'se-sk-5',
      name: 'High-Stakes Architecture & Tradeoff Evaluation',
      category: 'human_edge',
      isCurrent: false,
      isTarget: true,
      priority: 'high',
      description: 'Discerning when NOT to use AI, balancing distributed complexity against maintenance overhead.',
      recommendedWeek: 4
    },
    {
      id: 'se-sk-6',
      name: 'Code Verification & Rigorous Review Intuition',
      category: 'human_edge',
      isCurrent: true,
      isTarget: true,
      priority: 'high',
      description: 'Spotting subtle edge bugs, race conditions, and phantom logic generated by AI.',
      recommendedWeek: 5
    },
    {
      id: 'se-sk-7',
      name: 'Problem Decomposition & Prompt Architecture',
      category: 'human_edge',
      isCurrent: true,
      isTarget: true,
      priority: 'foundational',
      description: 'Breaking down ambiguous customer pain into crisp, testable modular specifications.',
      recommendedWeek: 1
    },
    // Domain Mastery
    {
      id: 'se-sk-8',
      name: 'Full-Stack TypeScript & Modern Web Protocols',
      category: 'domain_mastery',
      isCurrent: true,
      isTarget: true,
      priority: 'foundational',
      description: 'Deep mastery of event lifecycles, HTTP streaming, WebSockets, and state stores.',
      recommendedWeek: 2
    },
    {
      id: 'se-sk-9',
      name: 'System Observability, Telemetry & OpenTelemetry',
      category: 'domain_mastery',
      isCurrent: false,
      isTarget: true,
      priority: 'medium',
      description: 'Tracing distributed services, latency bottlenecks, and error budgets in real time.',
      recommendedWeek: 7
    }
  ],
  content_marketing: [
    {
      id: 'cm-sk-1',
      name: 'AI Prompt Engineering for Brand Voice & Tone Consistency',
      category: 'ai_tooling',
      isCurrent: false,
      isTarget: true,
      priority: 'high',
      description: 'Codifying style guides, vocabulary constraints, and tone guardrails into reusable system prompts.',
      recommendedWeek: 2
    },
    {
      id: 'cm-sk-2',
      name: 'Automated Content Ops & Repurposing Pipelines',
      category: 'ai_tooling',
      isCurrent: false,
      isTarget: true,
      priority: 'high',
      description: 'Using Zapier/Make and LLM webhooks to turn long-form recordings into multi-channel campaigns.',
      recommendedWeek: 4
    },
    {
      id: 'cm-sk-3',
      name: 'Editorial Taste & "Anti-Slop" Curation',
      category: 'human_edge',
      isCurrent: true,
      isTarget: true,
      priority: 'high',
      description: 'Stripping out generic AI fluff and infusing genuine point-of-view, humor, and provocative hooks.',
      recommendedWeek: 5
    },
    {
      id: 'cm-sk-4',
      name: 'Original Research & Proprietary Data Storytelling',
      category: 'human_edge',
      isCurrent: false,
      isTarget: true,
      priority: 'high',
      description: 'Designing customer surveys and industry benchmarks that AI cannot simulate.',
      recommendedWeek: 6
    },
    {
      id: 'cm-sk-5',
      name: 'Community Trust & Relationship Distribution',
      category: 'human_edge',
      isCurrent: true,
      isTarget: true,
      priority: 'medium',
      description: 'Nurturing relationships with creators, newsletter editors, and podcast hosts for organic reach.',
      recommendedWeek: 7
    },
    {
      id: 'cm-sk-6',
      name: 'Search & Generative Engine Optimization (GEO)',
      category: 'domain_mastery',
      isCurrent: false,
      isTarget: true,
      priority: 'high',
      description: 'Optimizing brand visibility inside Perplexity, ChatGPT Search, and Gemini Overviews.',
      recommendedWeek: 3
    }
  ],
  product_designer: [
    {
      id: 'pd-sk-1',
      name: 'Generative UI & Dynamic Canvas Design',
      category: 'ai_tooling',
      isCurrent: false,
      isTarget: true,
      priority: 'high',
      description: 'Designing interfaces that reconfigure themselves based on user intent rather than static trees.',
      recommendedWeek: 3
    },
    {
      id: 'pd-sk-2',
      name: 'AI Prototyping (v0, Lovable, Claude Artifacts)',
      category: 'ai_tooling',
      isCurrent: true,
      isTarget: true,
      priority: 'high',
      description: 'Generating clickable functional prototypes directly in code within minutes.',
      recommendedWeek: 2
    },
    {
      id: 'pd-sk-3',
      name: 'Conversational UX & Non-Deterministic Feedback Loops',
      category: 'human_edge',
      isCurrent: false,
      isTarget: true,
      priority: 'high',
      description: 'Guiding users through ambiguous AI outputs with graceful fallbacks and clear control knobs.',
      recommendedWeek: 5
    },
    {
      id: 'pd-sk-4',
      name: 'Cognitive Ergonomics & Human Attention Ethics',
      category: 'human_edge',
      isCurrent: true,
      isTarget: true,
      priority: 'medium',
      description: 'Protecting users from cognitive overload and manipulative interaction patterns.',
      recommendedWeek: 6
    },
    {
      id: 'pd-sk-5',
      name: 'Design Systems Tokenization & Code-Synced Atoms',
      category: 'domain_mastery',
      isCurrent: true,
      isTarget: true,
      priority: 'foundational',
      description: 'Maintaining bidirectional design tokens connecting Figma variables to Tailwind and CSS.',
      recommendedWeek: 4
    }
  ],
  financial_analyst: [
    {
      id: 'fa-sk-1',
      name: 'Python for Automated Financial Data Pipelines',
      category: 'ai_tooling',
      isCurrent: false,
      isTarget: true,
      priority: 'high',
      description: 'Writing scripts to ingest SEC filings, ERP databases, and market feeds automatically.',
      recommendedWeek: 3
    },
    {
      id: 'fa-sk-2',
      name: 'LLM Document Parsing & Contract Extraction',
      category: 'ai_tooling',
      isCurrent: false,
      isTarget: true,
      priority: 'high',
      description: 'Extracting balance sheet footnotes, covenant compliance, and debt maturity schedules via LLMs.',
      recommendedWeek: 2
    },
    {
      id: 'fa-sk-3',
      name: 'Strategic Capital Allocation & Executive Storytelling',
      category: 'human_edge',
      isCurrent: true,
      isTarget: true,
      priority: 'high',
      description: 'Framing complex financial scenario modeling in clear, actionable business recommendations.',
      recommendedWeek: 5
    },
    {
      id: 'fa-sk-4',
      name: 'Assumption Stress-Testing & Model Skepticism',
      category: 'human_edge',
      isCurrent: true,
      isTarget: true,
      priority: 'high',
      description: 'Challenging macro variables, inflation expectations, and outlier black-swan risks.',
      recommendedWeek: 6
    }
  ],
  customer_success: [
    {
      id: 'cs-sk-1',
      name: 'AI Agent Triage & Knowledge Base RAG Tuning',
      category: 'ai_tooling',
      isCurrent: false,
      isTarget: true,
      priority: 'high',
      description: 'Configuring enterprise support bots, knowledge embeddings, and human escalation triggers.',
      recommendedWeek: 2
    },
    {
      id: 'cs-sk-2',
      name: 'Predictive Health Scoring & Telemetry Dashboards',
      category: 'ai_tooling',
      isCurrent: false,
      isTarget: true,
      priority: 'high',
      description: 'Using customer usage analytics to preemptively detect churn signals before renewals.',
      recommendedWeek: 4
    },
    {
      id: 'cs-sk-3',
      name: 'Executive Relationship Management & High-Stakes Negotiation',
      category: 'human_edge',
      isCurrent: true,
      isTarget: true,
      priority: 'high',
      description: 'Building rapport with C-suite stakeholders and negotiating multi-year renewals.',
      recommendedWeek: 5
    },
    {
      id: 'cs-sk-4',
      name: 'Empathy in Crisis & De-escalation Mastery',
      category: 'human_edge',
      isCurrent: true,
      isTarget: true,
      priority: 'foundational',
      description: 'Calming stressed partners during outages with reassuring, solution-oriented composure.',
      recommendedWeek: 6
    }
  ],
  project_manager: [
    {
      id: 'pm-sk-1',
      name: 'Automated Project Operations & AI Synthesis',
      category: 'ai_tooling',
      isCurrent: false,
      isTarget: true,
      priority: 'high',
      description: 'Automating standup rollups, risk matrices, and dependency graphs with AI agents.',
      recommendedWeek: 3
    },
    {
      id: 'pm-sk-2',
      name: 'Psychological Safety & Conflict Mediation',
      category: 'human_edge',
      isCurrent: true,
      isTarget: true,
      priority: 'high',
      description: 'Aligning diverging opinions between technical leaders and executive management.',
      recommendedWeek: 5
    }
  ],
  hr_people: [
    {
      id: 'hr-sk-1',
      name: 'Ethical AI Hiring & Bias Audit Protocols',
      category: 'ai_tooling',
      isCurrent: false,
      isTarget: true,
      priority: 'high',
      description: 'Evaluating automated screening algorithms for compliance, equity, and transparency.',
      recommendedWeek: 3
    },
    {
      id: 'hr-sk-2',
      name: 'Empathetic Career Coaching & Retention Systems',
      category: 'human_edge',
      isCurrent: true,
      isTarget: true,
      priority: 'high',
      description: 'Guiding employees through organizational transitions and career evolution paths.',
      recommendedWeek: 5
    }
  ],
  custom: [
    {
      id: 'c-sk-1',
      name: 'Applied Prompt Engineering & Context Grounding',
      category: 'ai_tooling',
      isCurrent: false,
      isTarget: true,
      priority: 'high',
      description: 'Framing complex tasks with structured context, persona guidelines, and edge-case boundaries.',
      recommendedWeek: 2
    },
    {
      id: 'c-sk-2',
      name: 'Critical Verification & Quality Oversight',
      category: 'human_edge',
      isCurrent: true,
      isTarget: true,
      priority: 'high',
      description: 'Validating facts, tone, and strategic coherence before publishing or executing AI work.',
      recommendedWeek: 5
    }
  ]
};
